sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client/ 

script:
  - docker  run -e CI=true react-test npm run test 

after_success:
  - docker build -t amitsinha98/multi-client ./client/ 
  - docker build -t amitsinha98/multi-nginx ./nginx/ 
  - docker build -t amitsinha98/multi-server ./server/ 
  - docker build -t amitsinha98/multi-worker ./worker/

  #Login in Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push amitsinha98/multi-client
  - docker push amitsinha98/multi-nginx
  - docker push amitsinha98/multi-server
  - docker push amitsinha98/multi-worker 

